# File: .github/workflows/workflow.yml
on: [push]

name: example

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    
    - uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - uses: okteto/namespace@latest
    
    - name: "Create stack"
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
        file: ${{ github.workspace }}/backend/docker-compose.yml
